/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'primary-fixed': '#d8e2ff',
        'on-primary-container': '#00285d',
        'error-container': '#93000a',
        'tertiary-fixed': '#ffdcc6',
        'primary-fixed-dim': '#adc6ff',
        'on-background': '#e1e2ec',
        'secondary-fixed': '#e9ddff',
        'surface-dim': '#10131a',
        'tertiary-fixed-dim': '#ffb786',
        tertiary: '#ffb786',
        'surface-container': '#1d2027',
        'on-primary-fixed': '#001a42',
        'on-tertiary': '#502400',
        'on-secondary': '#3c0091',
        'secondary-container': '#571bc1',
        'primary-container': '#4d8eff',
        surface: '#10131a',
        'on-surface-variant': '#c2c6d6',
        'secondary-fixed-dim': '#d0bcff',
        'on-primary-fixed-variant': '#004395',
        secondary: '#d0bcff',
        'on-error': '#690005',
        background: '#10131a',
        'surface-variant': '#32353c',
        'surface-container-lowest': '#0b0e15',
        'on-secondary-fixed': '#23005c',
        'inverse-surface': '#e1e2ec',
        'surface-container-high': '#272a31',
        'on-tertiary-container': '#461f00',
        'inverse-on-surface': '#2e3038',
        outline: '#8c909f',
        'on-primary': '#002e6a',
        'on-error-container': '#ffdad6',
        'inverse-primary': '#005ac2',
        'on-tertiary-fixed-variant': '#723600',
        'surface-bright': '#363941',
        error: '#ffb4ab',
        'on-secondary-container': '#c4abff',
        'surface-container-low': '#191b23',
        'surface-container-highest': '#32353c',
        primary: '#adc6ff',
        'on-surface': '#e1e2ec',
        'on-secondary-fixed-variant': '#5516be',
        'tertiary-container': '#df7412',
        'outline-variant': '#424754',
        'on-tertiary-fixed': '#311400',
        'surface-tint': '#adc6ff',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        xl: '32px',
        sm: '8px',
        md: '16px',
        xs: '4px',
        lg: '24px',
        gutter: '20px',
        unit: '4px',
        'margin-page': '40px',
      },
      fontFamily: {
        'body-base': ['Inter', 'sans-serif'],
        'label-caps': ['Space Grotesk', 'sans-serif'],
        'code-base': ['Space Grotesk', 'monospace'],
        h2: ['Inter', 'sans-serif'],
        h1: ['Inter', 'sans-serif'],
        'body-sm': ['Inter', 'sans-serif'],
        'code-md': ['Space Grotesk', 'monospace'],
      },
      fontSize: {
        'body-base': ['14px', { lineHeight: '1.6', letterSpacing: '0em', fontWeight: '400' }],
        'label-caps': ['11px', { lineHeight: '1', letterSpacing: '0.05em', fontWeight: '600' }],
        'code-base': ['13px', { lineHeight: '1.6', letterSpacing: '0em', fontWeight: '400' }],
        h2: ['24px', { lineHeight: '1.3', letterSpacing: '-0.01em', fontWeight: '600' }],
        h1: ['32px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-sm': ['13px', { lineHeight: '1.5', letterSpacing: '0em', fontWeight: '400' }],
        'code-md': ['14px', { lineHeight: '1.4', letterSpacing: '0em', fontWeight: '500' }],
      },
    },
  },
  plugins: [
    require('@tailwindcss/typography'),
  ],
}
